Feature/gallery
Dmytro-Pinchuk/gr12-ice-cream-project pull request #12
Opened 2022-09-17 16:00 UTC by Belik1989

глянь до слайдів будь ласка. не можу з розмірами розібратись. ширина і висота. ширину не хочеться задавати статичну,і не можу зрозуміти до чого його треба позіціїнувати щоб було схоже на макет

2022-09-17 17:02 UTC, DenFedor commented
> глянь до слайдів будь ласка. не можу з розмірами розібратись. ширина і висота. ширину не хочеться задавати статичну,і не можу зрозуміти до чого його треба позіціїнувати щоб було схоже на макет

Привіт. З приводу зображень бекграунду. Подивись уважно на бекграунд в мобільній верстці. Там дизайнер накосячив і там в них є 2 точки від слайдера. Оптимізовані зображення  без точок цих бекграундів вже є на мейні, я залив для своєї секції images/cusomer_review без точок. Треба буде винести бекграунди в окрему папку для загального користування.

З приводу позиціонування. Зараз подивлюся твою гілку.

2022-09-17 17:20 UTC, Dmytro-Pinchuk requested changes
Файли типу ice cream (copy) треба назвати правильно, і ще не розумію, чому вони у форматі zip. Також давай поки що зробимо бекграунди так як є на макеті завта може порадимося із ментором щодо цієї лажі.

2022-09-17 17:20 UTC, Dmytro-Pinchuk commented on src/partials/gallery.html
> +        <source
Source ми пишемо всередені батьківського тега pictuare, а в тебе div

2022-09-18 08:03 UTC, Dmytro-Pinchuk approved these changes

2022-09-18 08:03 UTC, merged